// Code generated by thriftrw-plugin-yarpc
// @generated

package secondserviceclient

import (
	"github.com/thriftrw/thriftrw-go/protocol"
	"golang.org/x/net/context"
	"github.com/yarpc/yarpc-go"
	"github.com/yarpc/yarpc-go/crossdock/thrift/gauntlet/service/secondservice"
	"github.com/yarpc/yarpc-go/transport"
	"github.com/yarpc/yarpc-go/encoding/thrift"
	"github.com/thriftrw/thriftrw-go/wire"
)

// Interface is a client for the SecondService service.
type Interface interface {
	BlahBlah(
		ctx context.Context,
		reqMeta yarpc.CallReqMeta,
	) (yarpc.CallResMeta, error)

	SecondtestString(
		ctx context.Context,
		reqMeta yarpc.CallReqMeta,
		thing *string,
	) (string, yarpc.CallResMeta, error)
}

// New builds a new client for the SecondService service.
//
// 	client := secondserviceclient.New(dispatcher.Channel("secondservice"))
func New(c transport.Channel, opts ...thrift.ClientOption) Interface {
	return client{c: thrift.New(thrift.Config{
		Service:  "SecondService",
		Channel:  c,
		Protocol: protocol.Binary,
	}, opts...)}
}

type client struct{ c thrift.Client }

func (c client) BlahBlah(
	ctx context.Context, reqMeta yarpc.CallReqMeta,
) (resMeta yarpc.CallResMeta, err error) {
	args := secondservice.BlahBlahHelper.Args()

	var body wire.Value
	body, resMeta, err = c.c.Call(ctx, reqMeta, args)
	if err != nil {
		return
	}

	var result secondservice.BlahBlahResult
	if err = result.FromWire(body); err != nil {
		return
	}

	err = secondservice.BlahBlahHelper.UnwrapResponse(&result)
	return
}

func (c client) SecondtestString(
	ctx context.Context, reqMeta yarpc.CallReqMeta,
	_Thing *string,
) (success string, resMeta yarpc.CallResMeta, err error) {
	args := secondservice.SecondtestStringHelper.Args(_Thing)

	var body wire.Value
	body, resMeta, err = c.c.Call(ctx, reqMeta, args)
	if err != nil {
		return
	}

	var result secondservice.SecondtestStringResult
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = secondservice.SecondtestStringHelper.UnwrapResponse(&result)
	return
}
