// Code generated by thriftrw

package echo

import "github.com/thriftrw/thriftrw-go/wire"

type Ping struct{ Beep string }

func (v *Ping) ToWire() wire.Value {
	var fs [1]wire.Field
	i := 0
	fs[i] = wire.Field{ID: 1, Value: wire.NewValueString(v.Beep)}
	i++
	return wire.NewValueStruct(wire.Struct{Fields: fs[:i]})
}

func (v *Ping) FromWire(w wire.Value) error {
	var err error
	for _, f := range w.GetStruct().Fields {
		switch f.ID {
		case 1:
			if f.Value.Type() == wire.TBinary {
				v.Beep, err = f.Value.GetString(), error(nil)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func _Ping_Read(w wire.Value) (*Ping, error) {
	var v Ping
	err := v.FromWire(w)
	return &v, err
}

type Pong struct{ Boop string }

func (v *Pong) ToWire() wire.Value {
	var fs [1]wire.Field
	i := 0
	fs[i] = wire.Field{ID: 1, Value: wire.NewValueString(v.Boop)}
	i++
	return wire.NewValueStruct(wire.Struct{Fields: fs[:i]})
}

func (v *Pong) FromWire(w wire.Value) error {
	var err error
	for _, f := range w.GetStruct().Fields {
		switch f.ID {
		case 1:
			if f.Value.Type() == wire.TBinary {
				v.Boop, err = f.Value.GetString(), error(nil)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func _Pong_Read(w wire.Value) (*Pong, error) {
	var v Pong
	err := v.FromWire(w)
	return &v, err
}
