codecov:
  branch: dev

coverage:
  range: 50...90

  status:
    project:
      default: off
      main:
        target: 80%
        flags: main
      experimental:
        target: 70%
        flags: experimental
    patch: no

ignore:
  # All packages with .nocover files in them MUST be listed here
 - /encoding/thrift/internal/
 - /encoding/x/protobuf/internal/wirepb/
 - /internal/crossdock/client/dispatcher/
 - /internal/crossdock/crossdockpb/
 - /internal/crossdock/thrift/
 - /internal/crossdock/thrift/echo/
 - /internal/crossdock/thrift/echo/echoclient/
 - /internal/crossdock/thrift/echo/echoserver/
 - /internal/crossdock/thrift/echo/yarpc/
 - /internal/crossdock/thrift/gauntlet/
 - /internal/crossdock/thrift/gauntlet/secondserviceclient/
 - /internal/crossdock/thrift/gauntlet/secondserviceserver/
 - /internal/crossdock/thrift/gauntlet/thrifttestclient/
 - /internal/crossdock/thrift/gauntlet/thrifttestserver/
 - /internal/crossdock/thrift/gauntlet/yarpc/
 - /internal/crossdock/thrift/gen-go/
 - /internal/crossdock/thrift/gen-go/echo/
 - /internal/crossdock/thrift/gen-go/gauntlet_apache/
 - /internal/crossdock/thrift/gen-go/gauntlet_tchannel/
 - /internal/crossdock/thrift/oneway/
 - /internal/crossdock/thrift/oneway/onewayclient/
 - /internal/crossdock/thrift/oneway/onewayserver/
 - /internal/crossdock/thrift/oneway/yarpc/
 - /internal/examples/json-keyvalue/client
 - /internal/examples/json-keyvalue/server
 - /internal/examples/protobuf
 - /internal/examples/protobuf/example
 - /internal/examples/protobuf/examplepb
 - /internal/examples/protobuf/exampleutil
 - /internal/examples/thrift-hello/hello
 - /internal/examples/thrift-hello/hello/echo
 - /internal/examples/thrift-hello/hello/echo/helloclient
 - /internal/examples/thrift-hello/hello/echo/helloserver
 - /internal/examples/thrift-hello/hello/echo/hellotest
 - /internal/examples/thrift-keyvalue/keyvalue/client
 - /internal/examples/thrift-keyvalue/keyvalue/kv
 - /internal/examples/thrift-keyvalue/keyvalue/kv/keyvalueclient
 - /internal/examples/thrift-keyvalue/keyvalue/kv/keyvalueserver
 - /internal/examples/thrift-keyvalue/keyvalue/kv/keyvaluetest
 - /internal/examples/thrift-keyvalue/keyvalue/server
 - /internal/examples/thrift-oneway
 - /internal/examples/thrift-oneway/sink
 - /internal/examples/thrift-oneway/sink/helloclient
 - /internal/examples/thrift-oneway/sink/helloserver
 - /internal/examples/thrift-oneway/sink/hellotest
 - /internal/mapdecode/mapstructure/
 - /internal/service-test/
 - /yarpcproto/
