codecov:
  branch: dev

coverage:
  status:
    project:
      default: off
      main:
        target: 80%
        flags: main
      experimental:
        target: 70%
        flags: experimental

flags:
  main: {}

  experimental:
    paths:
      - encoding/x
      - peer/x
      - transport/x
      - x
