FROM golang:1.8.0

ENV SUPPRESS_DOCKER 1
WORKDIR /go/src/go.uber.org/yarpc
RUN apt-get update -yq && apt-get install -yq jq unzip
ADD glide.yaml glide.lock dockerdeps.mk /go/src/go.uber.org/yarpc/
ADD build/base.mk build/deps.mk /go/src/go.uber.org/yarpc/build/
ADD scripts/vendor-build.sh /go/src/go.uber.org/yarpc/scripts/
RUN make -f dockerdeps.mk deps
ADD . /go/src/go.uber.org/yarpc/
