FROM golang:1.12

ENV SUPPRESS_DOCKER 1
WORKDIR /yarpc
RUN apt-get update -yq && apt-get install -yq jq unzip netcat
ADD dockerdeps.mk /yarpc/
ADD etc/make/base.mk etc/make/deps.mk /yarpc/etc/make/
RUN make -f dockerdeps.mk predeps
ADD etc/bin/vendor-build.sh /yarpc/etc/bin/
ADD tools.go go.mod go.sum /yarpc/
RUN go mod download
RUN make -f dockerdeps.mk deps
ADD . /yarpc/
