FROM golang:1.8.0

EXPOSE 8080-8088
ENV SUPPRESS_DOCKER 1
WORKDIR /go/src/go.uber.org/yarpc
ADD dockercrossdockdeps.mk /go/src/go.uber.org/yarpc/
ADD build/base.mk build/deps.mk build/crossdockdeps.mk /go/src/go.uber.org/yarpc/build/
RUN make -f dockercrossdockdeps.mk crossdock-predeps
ADD glide.yaml glide.lock /go/src/go.uber.org/yarpc/
RUN make -f dockercrossdockdeps.mk glide
ADD . /go/src/go.uber.org/yarpc/
RUN go install ./internal/crossdock
CMD ["/go/bin/crossdock"]
