// Code generated by thriftrw v1.6.0. DO NOT EDIT.
// @generated

package common

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type BaseService_Healthy_Args struct{}

func (v *BaseService_Healthy_Args) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *BaseService_Healthy_Args) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *BaseService_Healthy_Args) String() string {
	if v == nil {
		return "<nil>"
	}
	var fields [0]string
	i := 0
	return fmt.Sprintf("BaseService_Healthy_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *BaseService_Healthy_Args) Equals(rhs *BaseService_Healthy_Args) bool {
	return true
}

func (v *BaseService_Healthy_Args) MethodName() string {
	return "healthy"
}

func (v *BaseService_Healthy_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var BaseService_Healthy_Helper = struct {
	Args           func() *BaseService_Healthy_Args
	IsException    func(error) bool
	WrapResponse   func(bool, error) (*BaseService_Healthy_Result, error)
	UnwrapResponse func(*BaseService_Healthy_Result) (bool, error)
}{}

func init() {
	BaseService_Healthy_Helper.Args = func() *BaseService_Healthy_Args {
		return &BaseService_Healthy_Args{}
	}
	BaseService_Healthy_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	BaseService_Healthy_Helper.WrapResponse = func(success bool, err error) (*BaseService_Healthy_Result, error) {
		if err == nil {
			return &BaseService_Healthy_Result{Success: &success}, nil
		}
		return nil, err
	}
	BaseService_Healthy_Helper.UnwrapResponse = func(result *BaseService_Healthy_Result) (success bool, err error) {
		if result.Success != nil {
			success = *result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type BaseService_Healthy_Result struct {
	Success *bool `json:"success,omitempty"`
}

func (v *BaseService_Healthy_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = wire.NewValueBool(*(v.Success)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("BaseService_Healthy_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *BaseService_Healthy_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TBool {
				var x bool
				x, err = field.Value.GetBool(), error(nil)
				v.Success = &x
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("BaseService_Healthy_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *BaseService_Healthy_Result) String() string {
	if v == nil {
		return "<nil>"
	}
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", *(v.Success))
		i++
	}
	return fmt.Sprintf("BaseService_Healthy_Result{%v}", strings.Join(fields[:i], ", "))
}

func _Bool_EqualsPtr(lhs, rhs *bool) bool {
	if lhs != nil && rhs != nil {
		x := *lhs
		y := *rhs
		return (x == y)
	}
	return lhs == nil && rhs == nil
}

func (v *BaseService_Healthy_Result) Equals(rhs *BaseService_Healthy_Result) bool {
	if !_Bool_EqualsPtr(v.Success, rhs.Success) {
		return false
	}
	return true
}

func (v *BaseService_Healthy_Result) GetSuccess() (o bool) {
	if v.Success != nil {
		return *v.Success
	}
	return
}

func (v *BaseService_Healthy_Result) MethodName() string {
	return "healthy"
}

func (v *BaseService_Healthy_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
