// Code generated by thriftrw-plugin-yarpc
// @generated

package emptyservicefx

import (
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/encoding/thrift"
	"go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/common/emptyserviceclient"
)

// Client provides a EmptyService client to an Fx application using the given name
// for routing.
//
// 	fx.Provide(
// 		emptyservicefx.Client("..."),
// 		newHandler,
// 	)
func Client(name string, opts ...thrift.ClientOption) interface{} {
	return func(d *yarpc.Dispatcher) emptyserviceclient.Interface {
		return emptyserviceclient.New(d.ClientConfig(name), opts...)
	}
}
