// Code generated by thriftrw
// @generated

package thrifttest

import (
	"errors"
	"fmt"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type TestByteArgs struct {
	Thing *int8 `json:"thing,omitempty"`
}

func (v *TestByteArgs) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Thing != nil {
		w, err = wire.NewValueI8(*(v.Thing)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *TestByteArgs) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TI8 {
				var x int8
				x, err = field.Value.GetI8(), error(nil)
				v.Thing = &x
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *TestByteArgs) String() string {
	var fields [1]string
	i := 0
	if v.Thing != nil {
		fields[i] = fmt.Sprintf("Thing: %v", *(v.Thing))
		i++
	}
	return fmt.Sprintf("TestByteArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *TestByteArgs) MethodName() string {
	return "testByte"
}

func (v *TestByteArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type TestByteResult struct {
	Success *int8 `json:"success,omitempty"`
}

func (v *TestByteResult) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = wire.NewValueI8(*(v.Success)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("TestByteResult should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *TestByteResult) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TI8 {
				var x int8
				x, err = field.Value.GetI8(), error(nil)
				v.Success = &x
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("TestByteResult should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *TestByteResult) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", *(v.Success))
		i++
	}
	return fmt.Sprintf("TestByteResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *TestByteResult) MethodName() string {
	return "testByte"
}

func (v *TestByteResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var TestByteHelper = struct {
	IsException    func(error) bool
	Args           func(thing *int8) *TestByteArgs
	WrapResponse   func(int8, error) (*TestByteResult, error)
	UnwrapResponse func(*TestByteResult) (int8, error)
}{}

func init() {
	TestByteHelper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	TestByteHelper.Args = func(thing *int8) *TestByteArgs {
		return &TestByteArgs{Thing: thing}
	}
	TestByteHelper.WrapResponse = func(success int8, err error) (*TestByteResult, error) {
		if err == nil {
			return &TestByteResult{Success: &success}, nil
		}
		return nil, err
	}
	TestByteHelper.UnwrapResponse = func(result *TestByteResult) (success int8, err error) {
		if result.Success != nil {
			success = *result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}
