// Code generated by thriftrw-plugin-yarpc
// @generated

// Package testservicefx provides better integration for Fx for services
// implementing or calling TestService.
//
// # Clients
//
// If you are making requests to TestService, use the Client function to inject a
// TestService client into your container.
//
//	fx.Provide(testservicefx.Client("..."))
//
// # Servers
//
// If you are implementing TestService, provide a testserviceserver.Interface into
// the container and use the Server function.
//
// Given,
//
//	func NewTestServiceHandler() testserviceserver.Interface
//
// You can do the following to have the procedures of TestService made available
// to an Fx application.
//
//	fx.Provide(
//		NewTestServiceHandler,
//		testservicefx.Server(),
//	)
package testservicefx
