// Code generated by thriftrw-plugin-yarpc
// @generated

package extendonlyclient

import (
	yarpc "go.uber.org/yarpc/v2"
	"go.uber.org/yarpc/v2/yarpcthrift"
	"go.uber.org/yarpc/v2/yarpcthrift/thriftrw-plugin-yarpc2/internal/tests/common/baseserviceclient"
)

// Interface is a client for the ExtendOnly service.
type Interface interface {
	baseserviceclient.Interface
}

// New builds a new client for the ExtendOnly service.
//
//  yarpcClient, _ := yarpc.ClientProvider("extendonly")
// 	client := extendonlyclient.New(yarpcClient)
func New(c yarpc.Client, opts ...yarpcthrift.ClientOption) Interface {
	return client{
		c: yarpcthrift.New(
			c,
			"ExtendOnly",
			opts...),
		Interface: baseserviceclient.New(c, opts...),
	}
}

type client struct {
	baseserviceclient.Interface

	c yarpcthrift.Client
}
