steps:
  - name: ":docker: :package: 1.21"
    plugins:
      docker-compose#v5.2.0:
        build: yarpc-go-1.21
        push: yarpc-go-1.21:027047743804.dkr.ecr.us-east-2.amazonaws.com/uber:latest
    agents:
      queue: builders
  - name: ":docker: :package: 1.22"
    plugins:
      docker-compose#v5.2.0:
        build: yarpc-go-1.22
        push: yarpc-go-1.22:027047743804.dkr.ecr.us-east-2.amazonaws.com/uber:latest
    agents:
      queue: builders
  - wait
  - name: ":go: 1.21 test - %n"
    command: "make test"
    parallelism: 2
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.21
    agents:
      queue: workers
  - name: ":go: 1.21 examples"
    command: "make examples"
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.21
    agents:
      queue: workers
  - name: ":go: 1.22 test - %n"
    command: "make codecov"
    parallelism: 6
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.22
    agents:
      queue: workers
  - name: ":go: 1.22 crossdock"
    command: "make crossdock-codecov"
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.22
    agents:
      queue: workers
  - name: ":go: 1.22 lint"
    command: "make lint"
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.22
    agents:
      queue: workers
  - name: ":go: 1.22 examples"
    command: "make examples"
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.22
    agents:
      queue: workers
