steps:
  - name: ":docker: :package: 1.9"
    plugins:
      docker-compose#v2.0.0:
        build: yarpc-go-1.9
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - name: ":docker: :package: 1.10"
    plugins:
      docker-compose#v2.0.0:
        build: yarpc-go-1.10
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ":go: 1.9 test - %n"
    command: "make test"
    parallelism: 2
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.9
    agents:
      queue: workers
  - name: ":go: 1.9 lint"
    command: "make lint"
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.9
    agents:
      queue: workers
  - name: ":go: 1.9 examples"
    command: "make examples"
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.9
    agents:
      queue: workers
  - name: ":go: 1.10 test - %n"
    command: "make codecov"
    parallelism: 6
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.10
    agents:
      queue: workers
  - name: ":go: 1.10 lint"
    command: "make lint"
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.10
    agents:
      queue: workers
  - name: ":go: 1.10 examples"
    command: "make examples"
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.10
    agents:
      queue: workers
