steps:
  - name: ":docker: :package: 1.20"
    plugins:
      docker-compose#v2.0.0:
        build: yarpc-go-1.20
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ":go: 1.20 update-deps"
    command: "etc/bin/update-deps.sh"
    plugins:
      docker-compose#v2.0.0:
        run: yarpc-go-1.20
        env:
          # The script needs the following environment variables in addition
          # to those provided by the docker-compose.
          - GITHUB_USER
          - GITHUB_EMAIL
          - GITHUB_TOKEN
          - GITHUB_REPO
    agents:
      queue: workers
