steps:
  - name: ":docker: :package: 1.22"
    plugins:
      docker-compose#v5.2.0:
        build: yarpc-go-1.22
        push: yarpc-go-1.22:027047743804.dkr.ecr.us-east-2.amazonaws.com/uber:latest
    agents:
      queue: builders
  - wait
  - name: ":go: 1.22 update-deps"
    command: "etc/bin/update-deps.sh"
    plugins:
      docker-compose#v5.2.0:
        run: yarpc-go-1.22
        env:
          # The script needs the following environment variables in addition
          # to those provided by the docker-compose.
          - GITHUB_USER
          - GITHUB_EMAIL
          - GITHUB_TOKEN
          - GITHUB_REPO
    agents:
      queue: workers
