// Code generated by thriftrw-plugin-yarpc
// @generated

package NOSERVICES

// CustomerUUID returns the UUID string from the parameter annotated with auth.actor_uuid if present.
func (e *Struct) CustomerUUID() string {
	return e.uuid
}
