// Code generated by thriftrw-plugin-yarpc
// @generated

package readonlystoreserver

import (
	"context"
	"go.uber.org/thriftrw/wire"
	yarpc "go.uber.org/yarpc/v2"
	"go.uber.org/yarpc/v2/yarpcthrift"
	"go.uber.org/yarpc/v2/yarpcthrift/thriftrw-plugin-yarpc2/internal/tests/atomic"
	"go.uber.org/yarpc/v2/yarpcthrift/thriftrw-plugin-yarpc2/internal/tests/common/baseserviceserver"
)

// Interface is the server-side interface for the ReadOnlyStore service.
type Interface interface {
	baseserviceserver.Interface

	Integer(
		ctx context.Context,
		Key *string,
	) (int64, error)
}

// New prepares an implementation of the ReadOnlyStore service for
// registration.
//
// 	handler := ReadOnlyStoreHandler{}
// 	dispatcher.Register(readonlystoreserver.New(handler))
func New(impl Interface, opts ...yarpcthrift.RegisterOption) []yarpc.TransportProcedure {
	h := handler{impl}
	service := yarpcthrift.Service{
		Name: "ReadOnlyStore",
		Methods: []yarpcthrift.Method{

			yarpcthrift.Method{
				Name:         "integer",
				Handler:      yarpcthrift.Handler(h.Integer),
				Signature:    "Integer(Key *string) (int64)",
				ThriftModule: atomic.ThriftModule,
			},
		},
	}

	procedures := make([]yarpc.TransportProcedure, 0, 1)
	procedures = append(procedures, baseserviceserver.New(impl, opts...)...)
	procedures = append(procedures, yarpcthrift.BuildProcedures(service, opts...)...)
	return procedures
}

type handler struct{ impl Interface }

func (h handler) Integer(ctx context.Context, body wire.Value) (yarpcthrift.Response, error) {
	var args atomic.ReadOnlyStore_Integer_Args
	if err := args.FromWire(body); err != nil {
		return yarpcthrift.Response{}, err
	}

	success, appErr := h.impl.Integer(ctx, args.Key)

	result, err := atomic.ReadOnlyStore_Integer_Helper.WrapResponse(success, appErr)

	var response yarpcthrift.Response
	if err == nil {
		response.Exception = appErr
		response.Body = result
	}
	return response, err
}
