// Code generated by protoc-gen-go.

// Copyright (c) 2016 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// source: internal.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	ApplicationError
	Response
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ApplicationError is an error that occured in the application on the server-side.
type ApplicationError struct {
	// The message name as registered with github.com/golang/protobuf/proto#RegisterType.
	//
	// There is a generic way to represent message names (including package paths)
	// that is used in google/protobuf/descriptor.proto, this should be used.
	//
	// Note this is optional, if this is not set, payload is intepreted as a
	// protobuf string (either UTF-8 or 7-bit ASCII) as a generic error message.
	//
	// the method must have this message name marked as a potential error type using
	// option (yarpc.error_types). See yarpc.proto and annotations.proto.
	MessageName string `protobuf:"bytes,1,opt,name=message_name,json=messageName" json:"message_name,omitempty"`
	// The payload, either a protobuf message with name specified by message_name,
	// or a generic error. If a generic error, this will be a protobuf string.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ApplicationError) Reset()                    { *m = ApplicationError{} }
func (m *ApplicationError) String() string            { return proto.CompactTextString(m) }
func (*ApplicationError) ProtoMessage()               {}
func (*ApplicationError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApplicationError) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *ApplicationError) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Response contains the server-side response.
type Response struct {
	// The payload of the protobuf response. Type information is not needed
	// since this is part of the protobuf spec.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// An error, if one occurred.
	ApplicationError *ApplicationError `protobuf:"bytes,2,opt,name=ApplicationError" json:"ApplicationError,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Response) GetApplicationError() *ApplicationError {
	if m != nil {
		return m.ApplicationError
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplicationError)(nil), "internal.ApplicationError")
	proto.RegisterType((*Response)(nil), "internal.Response")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xfc,
	0xb9, 0x04, 0x1c, 0x0b, 0x0a, 0x72, 0x32, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x5c, 0x8b, 0x8a,
	0xf2, 0x8b, 0x84, 0x14, 0xb9, 0x78, 0x72, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xe3, 0xf3, 0x12,
	0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xb8, 0xa1, 0x62, 0x7e, 0x89, 0xb9, 0xa9,
	0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x30, 0xae, 0x52, 0x0e, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x31, 0x8a,
	0x2a, 0x46, 0x14, 0x55, 0x42, 0x6e, 0x98, 0xd6, 0x82, 0x0d, 0xe2, 0x36, 0x92, 0xd2, 0x83, 0xbb,
	0x15, 0x5d, 0x45, 0x10, 0x86, 0x9e, 0x24, 0x36, 0xb0, 0x7f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcb, 0x5b, 0x3f, 0x8e, 0xe1, 0x00, 0x00, 0x00,
}
