// Code generated by thriftrw-plugin-yarpc
// @generated

package bazfx

import (
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/encoding/thrift"
	"go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/extends/bazclient"
)

// Params defines the dependencies for the Baz client.
type Params struct {
	fx.In

	Provider yarpc.ClientConfig
}

// Result defines the output of the Baz client module. It provides a
// Baz client to an Fx application.
type Result struct {
	fx.Out

	Client bazclient.Interface

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// Client provides a Baz client to an Fx application using the given name
// for routing.
//
// 	fx.Provide(
// 		bazfx.Client("..."),
// 		newHandler,
// 	)
func Client(name string, opts ...thrift.ClientOption) interface{} {
	return func(p Params) Result {
		client := bazclient.New(p.Provider.ClientConfig(name), opts...)
		return Result{Client: client}
	}
}
