// Copyright (c) 2026 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"

	"go.uber.org/thriftrw/compile"
	"go.uber.org/thriftrw/plugin"
	"go.uber.org/thriftrw/plugin/api"
)

const (
	_UUIDAnnotationKey = "auth.actor_uuid"
)

// yarpcUUIDTemplate emits an ActorUUID() accessor for every Go type
// that thriftrw will generate from a Thrift declaration carrying an
// auth.actor_uuid-annotated field.
const yarpcUUIDTemplate = `
// Code generated by thriftrw-plugin-yarpc
// @generated

package <.Name>

<range $name, $t := .Types><with (uuidFieldOf $t)>
// ActorUUID returns the UUID string from the field annotated with
// auth.actor_uuid, or "" if it is unset.
func (t *<goCase $t.Name>) ActorUUID() string {
	return <if .IsTypedef>string(t.Get<goCase .Field.Name>())<else>t.Get<goCase .Field.Name>()<end>
}
<end><end>
<range $svcName, $svc := .Services><range $fnName, $fn := $svc.Functions><with (uuidFieldInArgs $fn)>
// ActorUUID returns the UUID string from the field annotated with
// auth.actor_uuid, or "" if it is unset.
func (t *<goCase $svc.Name>_<goCase $fn.Name>_Args) ActorUUID() string {
	return <if .IsStruct>t.Get<goCase .Field.Name>().ActorUUID()<else if .IsTypedef>string(t.Get<goCase .Field.Name>())<else>t.Get<goCase .Field.Name>()<end>
}
<end><end><end>
`

func yarpcUUIDGenerator(data *moduleTemplateData, files map[string][]byte) error {
	// kv.thrift => .../kv/types_yarpc_uuid.go
	path := filepath.Join(data.Module.Directory, "types_yarpc_uuid.go")

	// data.CompiledModule is the result of compiling the original Thrift file.
	// Plugins do not have access to it via the API, so it is compiled once in
	// Generate and shared across generators; this generator writes extra
	// methods to types annotated with auth.actor_uuid in that Thrift file.
	compiledModule := data.CompiledModule

	// Pre-flight pass over the same structures the template iterates,
	// enforcing the at-most-one-annotation-per-container invariant.
	// The file itself is always emitted (even when
	// no annotated fields exist, the output is a header-only package file)
	if err := validateUUIDAnnotations(compiledModule); err != nil {
		return err
	}

	templateOptions := append(templateOptions,
		plugin.TemplateFunc("uuidFieldOf", uuidFieldOf),
		plugin.TemplateFunc("uuidFieldInArgs", uuidFieldInArgs),
		plugin.TemplateFunc("goCase", goCase),
	)

	var err error
	files[path], err = plugin.GoFileFromTemplate(path, yarpcUUIDTemplate, compiledModule, templateOptions...)
	return err
}

// uuidArg is the single-value carrier the template's <with> rebinds
// dot to. It bundles the matched FieldSpec and two mutually-exclusive
// flags driving the body shape:
//   - IsStruct: the matched arg is itself a struct whose own field
//     carries the annotation, so the template chains ".ActorUUID()".
//   - IsTypedef: the matched field's type is a typedef, so the getter
//     returns the typedef rather than plain string and the template
//     wraps the call in "string(...)" to satisfy the func signature.
type uuidArg struct {
	Field     *compile.FieldSpec
	IsStruct  bool
	IsTypedef bool
}

// uuidFieldsOf returns every auth.actor_uuid-annotated field on a
// Thrift struct (including exception structs).
//
// The validator uses this to reject containers with more than one
// annotated field; the template-facing uuidFieldOf wraps it to return
// just the first hit.
func uuidFieldsOf(t compile.TypeSpec) []*uuidArg {
	ss, ok := t.(*compile.StructSpec)
	if !ok {
		return nil
	}
	var out []*uuidArg
	for _, f := range ss.Fields {
		if _, ok := f.Annotations[_UUIDAnnotationKey]; ok {
			_, isTypedef := f.Type.(*compile.TypedefSpec)
			out = append(out, &uuidArg{Field: f, IsTypedef: isTypedef})
		}
	}
	return out
}

// uuidFieldOf returns the first auth.actor_uuid-annotated field on a
// Thrift struct, or nil. Validation guarantees at most one match exists by the
// time the template runs.
func uuidFieldOf(t compile.TypeSpec) *uuidArg {
	if hits := uuidFieldsOf(t); len(hits) > 0 {
		return hits[0]
	}
	return nil
}

// uuidFieldsInArgs returns every arg in a service method's argument
// list that reaches an auth.actor_uuid annotation, either directly
// or one struct hop away.
//
// The validator uses this to reject method-args lists where more than
// one arg reaches an annotation; uuidFieldInArgs wraps it to return
// just the first hit, which is what the args-accessor emission needs.
func uuidFieldsInArgs(fn *compile.FunctionSpec) []*uuidArg {
	var out []*uuidArg
	for _, f := range fn.ArgsSpec {
		if _, ok := f.Annotations[_UUIDAnnotationKey]; ok {
			_, isTypedef := f.Type.(*compile.TypedefSpec)
			out = append(out, &uuidArg{Field: f, IsTypedef: isTypedef})
			continue
		}
		if uuidFieldOf(f.Type) != nil {
			out = append(out, &uuidArg{Field: f, IsStruct: true})
		}
	}
	return out
}

// uuidFieldInArgs returns the first arg that reaches an
// auth.actor_uuid annotation, or nil. Template-facing wrapper.
func uuidFieldInArgs(fn *compile.FunctionSpec) *uuidArg {
	if hits := uuidFieldsInArgs(fn); len(hits) > 0 {
		return hits[0]
	}
	return nil
}

// methodHasActorUUIDArg reports whether the given thriftrw plugin-API
// function has an argument that reaches an auth.actor_uuid annotation,
// either directly or through a struct-typed arg. The server template
// uses it to gate the per-method validator-call block and the
// per-method NoWire handler's validator field.
func methodHasActorUUIDArg(fn *api.Function, mod *compile.Module, serviceThriftName string) bool {
	if fn == nil {
		return false
	}
	compiled := lookupCompiledFunction(mod, serviceThriftName, fn.ThriftName)
	if compiled == nil {
		return false
	}
	return uuidFieldInArgs(compiled) != nil
}

// serviceHasActorUUIDMethod reports whether the given thriftrw plugin-API
// service has at least one method that reaches an auth.actor_uuid
// annotation. The server template uses it to gate the service-wide
// handler struct's validator field and its initialisation inside New.
func serviceHasActorUUIDMethod(svc *api.Service, mod *compile.Module) bool {
	if svc == nil || mod == nil {
		return false
	}
	compiled := mod.Services[svc.ThriftName]
	if compiled == nil {
		return false
	}
	for _, fn := range compiled.Functions {
		if uuidFieldInArgs(fn) != nil {
			return true
		}
	}
	return false
}

// validateUUIDAnnotations walks every struct in module.Types and every
// method-args list in module.Services and rejects any container that
// reaches the auth.actor_uuid annotation more than once, since each Go
// type can only carry one ActorUUID accessor.
func validateUUIDAnnotations(module *compile.Module) error {
	for _, t := range module.Types {
		ss, ok := t.(*compile.StructSpec)
		if !ok {
			continue
		}
		if err := tooManyAnnotations(uuidFieldsOf(ss), ss.Name); err != nil {
			return err
		}
	}

	for _, svc := range module.Services {
		for _, fn := range svc.Functions {
			ownerLabel := fmt.Sprintf("%s.%s", svc.Name, fn.Name)
			if err := tooManyAnnotations(uuidFieldsInArgs(fn), ownerLabel); err != nil {
				return err
			}
		}
	}

	return nil
}

// tooManyAnnotations returns an error naming the first two hits when
// more than one annotation was found in a single container.
func tooManyAnnotations(hits []*uuidArg, ownerLabel string) error {
	if len(hits) <= 1 {
		return nil
	}
	return fmt.Errorf(
		"multiple fields annotated with %s for %s. Prev %s; duplicate at %s",
		_UUIDAnnotationKey, ownerLabel, hits[0].Field.Name, hits[1].Field.Name)
}

// The block below (goCase, pascalCase, isAllCaps, commonInitialisms) is
// copy-pasted verbatim from go.uber.org/thriftrw's internal gen package:
//
//	https://github.com/thriftrw/thriftrw-go/blob/master/gen/string.go
//
// thriftrw uses these helpers to derive Go identifiers from Thrift names
// during code generation. They are unexported there, so we cannot import
// them. We need the exact same naming logic to refer to thriftrw-generated
// types and fields (e.g. an "actor_uuid" field becomes "ActorUUID", not
// "Actor_uuid"); diverging here would produce code that does not compile.
//
// TODO: upstream a change to thriftrw that exports goCase (or an equivalent)
// and switch this plugin to use the exported version, then delete this copy.
//
// Note: strings.Title is deprecated as of Go 1.18, but is intentionally kept
// here to match thriftrw's behaviour exactly.

// isAllCaps checks if a string contains all capital letters only. Non-letters
// are not considered.
func isAllCaps(s string) bool {
	for _, r := range s {
		if unicode.IsLetter(r) && !unicode.IsUpper(r) {
			return false
		}
	}
	return true
}

// pascalCase combines the given words using PascalCase.
//
// If allowAllCaps is true, when an all-caps word that is not a known
// abbreviation is encountered, it is left unchanged. Otherwise, it is
// Titlecased.
func pascalCase(allowAllCaps bool, words ...string) string {
	for i, chunk := range words {
		if len(chunk) == 0 {
			// foo__bar
			continue
		}

		// known initalism
		init := strings.ToUpper(chunk)
		if _, ok := commonInitialisms[init]; ok {
			words[i] = init
			continue
		}

		// Was SCREAMING_SNAKE_CASE and not a known initialism so Titlecase it.
		if isAllCaps(chunk) && !allowAllCaps {
			// A single ALLCAPS word does not count as SCREAMING_SNAKE_CASE.
			// There must be at least one underscore.
			words[i] = strings.Title(strings.ToLower(chunk))
			continue
		}

		// Just another word, but could already be camelCased somehow, so just
		// change the first letter.
		head, headIndex := utf8.DecodeRuneInString(chunk)
		words[i] = string(unicode.ToUpper(head)) + string(chunk[headIndex:])
	}

	return strings.Join(words, "")
}

// goCase converts strings into PascalCase.
func goCase(s string) string {
	if len(s) == 0 {
		panic(fmt.Sprintf("%q is not a valid identifier", s))
	}

	words := strings.Split(s, "_")
	return pascalCase(len(words) == 1 /* all caps */, words...)
	// goCase allows all caps only if the string is a single all caps word.
	// That is, "FOO" is allowed but "FOO_BAR" is changed to "FooBar".
}

var commonInitialisms = map[string]bool{
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SQL":   true,
	"SSH":   true,
	"TCP":   true,
	"TLS":   true,
	"TTL":   true,
	"UDP":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
	"XSRF":  true,
	"XSS":   true,
}
