// Code generated by thriftrw-plugin-yarpc
// @generated

package extendonlytest

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	yarpc "go.uber.org/yarpc"
	extendonlyclient "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/common/extendonlyclient"
)

// MockClient implements a gomock-compatible mock client for service
// ExtendOnly.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

var _ extendonlyclient.Interface = (*MockClient)(nil)

type _MockClientRecorder struct {
	mock *MockClient
}

// Build a new mock client for service ExtendOnly.
//
//	mockCtrl := gomock.NewController(t)
//	client := extendonlytest.NewMockClient(mockCtrl)
//
// Use EXPECT() to set expectations on the mock.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

// EXPECT returns an object that allows you to define an expectation on the
// ExtendOnly mock client.
func (m *MockClient) EXPECT() *_MockClientRecorder {
	return m.recorder
}

// Healthy responds to a Healthy call based on the mock expectations. This
// call will fail if the mock does not expect this call. Use EXPECT to expect
// a call to this function.
//
//	client.EXPECT().Healthy(gomock.Any(), ...).Return(...)
//	... := client.Healthy(...)
func (m *MockClient) Healthy(
	ctx context.Context,
	opts ...yarpc.CallOption,
) (success bool, err error) {

	args := []interface{}{ctx}
	for _, o := range opts {
		args = append(args, o)
	}
	i := 0
	ret := m.ctrl.Call(m, "Healthy", args...)
	success, _ = ret[i].(bool)
	i++
	err, _ = ret[i].(error)
	return
}

func (mr *_MockClientRecorder) Healthy(
	ctx interface{},
	opts ...interface{},
) *gomock.Call {
	args := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCall(mr.mock, "Healthy", args...)
}
